# Define the HTTP settings
httpClient:
  port: 8040
  adminPort: 8041

#taken from https://github.com/stakkTraze/dropwizard-atmosphere/blob/master/config.yml
server:
  applicationConnectors:
    - type: http
      port: 8040
      headerCacheSize: 512 bytes
      outputBufferSize: 32KiB
      maxRequestHeaderSize: 8KiB
      maxResponseHeaderSize: 8KiB
      inputBufferSize: 8KiB
      idleTimeout: 30 seconds
      minBufferPoolSize: 64 bytes
      bufferPoolIncrement: 1KiB
      maxBufferPoolSize: 64KiB
      acceptorThreads: 1
      selectorThreads: 2
      acceptQueueSize: 1024
      reuseAddress: true
      soLingerTime: 345s
      useServerHeader: false
      useDateHeader: true
      useForwardedHeaders: true

# Define the client settings for connecting to upstream data services
httpClient:
  timeout: 60s # Timeout while connecting, reading, or writing (Heroku needs large value for spin-up)
  timeToLive: 10m # Keep connections open
  cookiesEnabled: true # Track cookies
  gzipEnabled: true # Allow for gzipped request and response entities
  minThreads: 1
  maxThreads: 128 # Thread pool for JerseyClient's async requests

logging:
  level: DEBUG
  loggers:
    org.eclipse.jetty: OFF
  appenders:
    - type: console
#
privateKeyFile:
  D:/dev/workspaces/personale/rest-ms/auth-service/src/test/java/private.key
publicKeyFile:
  D:/dev/workspaces/personale/rest-ms/auth-service/src/test/java/public.key
